## elastic config
spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200  # ES的连接地址，多个地址用逗号分隔
      username: elastic                         # 用户名
      password: Cogiot@2021               # 密码
      connection-timeout: 60000           # 连接超时时间
      read-timeout: 60000                 # 读取超时时间


